ouvidoria-social/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI.WebControls;
using ouvidoria_social.Models;
using ouvidoria_social.Models.Adapter;
using ouvidoria_social.Models.Enum;
using ouvidoria_social.Models.Utils;
using Ouvidoria_Social_DataAccess;

namespace ouvidoria_social.Controllers
{
    public class AutenticacaoController : Controller
    {
        // GET: Autenticacao
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Logar(Usuario usuario)
        {
            var user = UsuarioRepository.AutenticaUsuario(usuario);

            if (user == null)
            {
                ViewBag.Error = "Nome do usuário ou senha inválidos";
                return View("Index");
            }

            if (user.Pessoa.IsAtivo == 'S')
            {
                return RedirectToAction("Perfil", "Usuario", new {Id = user.Pessoa.Id});
            }
            else
            {
                return View("Index");
            }
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Usuario usuario)
        {
            UsuarioRepository.CadastrarUsuario(usuario);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            UsuarioRepository.Deslogar();

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public PartialViewResult _AddPessoaView()
        {
            return PartialView("_AddPessoaView");
        }

        [HttpPost]
        public PartialViewResult AddPessoaAjax(Pessoa pessoa)
        {
            var model = ConnectionDbClass.DataModel;

            ViewBag.Tipo = 3;

            if (pessoa.Tipo == 'I')
            {
                var inst = model.Instituicaos.FirstOrDefault(w => (w.Nome.ToLower() == pessoa.Nome.ToLower()) || (w.Nome_fantasia.ToLower() == pessoa.Nome.ToLower()));

                if (inst != null)
                {
                    if (inst.Pessoas.Any())
                    {
                        if (inst.Pessoas[0].Usuarios.Count > 0)
                        {
                            ViewBag.Mensagem =
                                "Esta instituição já existe, e possui um usuário associado. Entre em contato com a mesma para obter mais detalhes.";
                            ViewBag.Tipo = 0;
                        }
                        else
                        {
                            ViewBag.Mensagem =
                                "Esta instituição já existe, entretanto não existe usuário associado a mesma, você irá cadastrá-lo.";
                            ViewBag.Tipo = 1;
                        }

                        Session["CadastroPessoa"] = inst.Pessoas[0];
                        return PartialView("_AddUsuario", null);
                    }
                    else
                    {
                        ViewBag.Mensagem =
                            "Esta instituição já existe, entretanto não existe usuário associado a mesma, você irá cadastrá-lo.";
                        ViewBag.Tipo = 1;
                    }

                    inst.Email = pessoa.Email;
                    inst.Telefone = pessoa.Telefone;

                    pessoa.Instituicao = inst;
                }
                else
                {
                    pessoa.Instituicao = new Instituicao()
                    {
                        Nome = pessoa.Nome,
                        Email = pessoa.Email,
                        Telefone = pessoa.Telefone
                    };
                }
            }
            
            Session["CadastroPessoa"] = pessoa;
            return PartialView("_AddUsuario", null);
        }

        [HttpPost]
        public PartialViewResult AddUsuarioAjax(UsuarioAdapter adapter)
        {

            var p = (Pessoa) Session["CadastroPessoa"];
            var model = ConnectionDbClass.DataModel;

            var usuario = adapter.ConvertToUsuario();
            usuario.Gamify = true;
            
            usuario.Pessoa = p;
            p.Usuarios.Add(usuario);

            ConnectionDbClass.DataModel.Add(p);
            
            if (model.HasChanges)
            {
                model.SaveChanges();
            }

            Session["CadastroPessoa"] = null;
            Session.Remove("CadastroPessoa");

            ViewData["Titulo"] = p.Nome;
            ViewData["Msg"] = "Seu Usuário foi criado com sucesso!";
            
            PontuacaoUtils.Pontuar(usuario.Pessoa, PontuacaoEnum.CadastroUsuario);

            return PartialView("_MensagemAlerta");
        }

        public ActionResult VerificaUsuario(string login)
        {
            if (Session["Usuario"] != null)
            {
                var user = (Usuario) Session["Usuario"];

                if (user.Login == login)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
            }

            var model = ConnectionDbClass.DataModel;

            var usuario = model.Usuarios.Where(w => w.Login == login).ToList();

            if (usuario.Count == 0)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            
        }

        public ActionResult VerificaSenhaAntiga(string OldPassword)
        {
            var usuario = (Usuario)Session["Usuario"];

            if (usuario.Senha == OldPassword)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ListaCidade(string uf)
        {
            var model = ConnectionDbClass.DataModel;
            
            var cidades = model.Cidades.Where(w => w.Uf == uf).ToList();

            var cities = CidadeAdapter.Adaptar(cidades);

            return Json(cities, JsonRequestBehavior.AllowGet);
        }
    }
}

ouvidoria-social/Controllers/OuvidoriaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ouvidoria_social.Models.Adapter;
using ouvidoria_social.Models.Enum;
using ouvidoria_social.Models.Utils;
using Ouvidoria_Social_DataAccess;
using WebGrease.Css.Extensions;

namespace ouvidoria_social.Controllers
{
    public class OuvidoriaController : Controller
    {
        // GET: Ouvidoria
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public PartialViewResult FiltrarReclamacoes(string stringBusca, bool isSolucionado, int tipoBusca)
        {
            var model = ConnectionDbClass.DataModel;

            var reclamacoes = model.Reclamacaos.Where(w => w.IsAtivo.Value).ToList();

            if (isSolucionado)
            {
                reclamacoes = reclamacoes.Where(w => w.IsSolucionado.Value == isSolucionado || 
                    w.Comentarios.Any(a => a.IsSolucao.Value == isSolucionado)).ToList();
            }

            if (!string.IsNullOrEmpty(stringBusca))
            {
                switch (tipoBusca)
                {
                    case 1:
                    {
                        reclamacoes = reclamacoes.Where(w => w.Pessoa.Nome.Trim().ToLower().Contains(stringBusca.Trim().ToLower())).ToList();
                        break;
                    }
                    case 2:
                    {
                        reclamacoes = reclamacoes.Where(w => w.Instituicao.Nome.Trim().ToLower().Contains(stringBusca.Trim().ToLower())).ToList();
                        break;
                    }
                    case 4:
                    {
                        reclamacoes = reclamacoes.Where(w => w.Titulo.Trim().ToLower().Contains(stringBusca.Trim().ToLower())).ToList();
                        break;
                    }
                    case 3:
                    {
                        reclamacoes = reclamacoes.Where(w => w.Descricao.Trim().ToLower().Contains(stringBusca.Trim().ToLower())).ToList();
                        break;
                    }
                    case 6:
                    {
                        reclamacoes = reclamacoes.Where(w => w.Departamento.Trim().ToLower().Contains(stringBusca.Trim().ToLower())).ToList();
                        break;
                    }
                    case 5:
                    {
                        reclamacoes = reclamacoes.Where(w => 
                            w.Titulo.Trim().ToLower().Contains(stringBusca.Trim().ToLower()) || 
                            w.Descricao.Trim().ToLower().Contains(stringBusca.Trim().ToLower()) || 
                            w.Instituicao.Nome.Trim().ToLower().Contains(stringBusca.Trim().ToLower()) || 
                            w.Pessoa.Nome.Trim().ToLower().Contains(stringBusca.Trim().ToLower()) ||
                            w.Departamento.Trim().ToLower().Contains(stringBusca.Trim().ToLower())
                        ).ToList();
                        break;
                    }
                }
            }

            reclamacoes = reclamacoes.OrderByDescending(o => o.DataHora).ToList();

            Session["ReclamacaoFiltro"] = reclamacoes;

            ViewData["Pagina"] = 1;

            return PartialView("_ReclamacoesRecentesView", reclamacoes);
        }

        public ActionResult Reclamacoes()
        {
            var model = ConnectionDbClass.DataModel;

            var recs = model.Reclamacaos.Where(w => w.IsAtivo.Value).OrderByDescending(o => o.DataHora).ToList();

            ViewBag.Pagina = 1;

            Session["ReclamacaoFiltro"] = recs;

            return View(recs);
        }

        [HttpPost]
        public PartialViewResult NavegarPaginaReclamacao(int pagina)
        {
            var model = ConnectionDbClass.DataModel;

            var recs = model.Reclamacaos.OrderByDescending(o => o.DataHora).ToList();
            if (Session["ReclamacaoFiltro"] != null)
            {
                recs = (List<Reclamacao>)Session["ReclamacaoFiltro"];
            }

            ViewData["Pagina"] = pagina;

            return PartialView("_ReclamacoesRecentesView", recs);
        }

        public ActionResult IncluirReclamacao()
        {
            return View();
        }

        public PartialViewResult _MarcarDesmarcarMelhorReposta(int id, int idRec, bool marcar)
        {
            var model = ConnectionDbClass.DataModel;

            var rec = model.Reclamacaos.FirstOrDefault(f => f.Id == idRec);

            Pessoa pessoa = null;

            if (rec != null)
            {
                var comentario = rec.Comentarios.FirstOrDefault(f => f.Id == id);

                if (comentario != null) comentario.IsSolucao = marcar;

                pessoa = comentario.Pessoa;

                Log_participapao log = null;
                if (marcar)
                {
                    log = new Log_participapao()
                    {
                        Acesso = false,
                        Datahora = DateTime.Now,
                        Id_pessoa = comentario.Id_pessoa,
                        Id_reclamacao = comentario.Id_reclamacao,
                        Tipo = "Macou como solução"
                    };
                }
                else
                {
                    log = new Log_participapao()
                    {
                        Acesso = false,
                        Datahora = DateTime.Now,
                        Id_pessoa = comentario.Id_pessoa,
                        Id_reclamacao = comentario.Id_reclamacao,
                        Tipo = "Desmacou como solução"
                    };
                }

                model.Add(log);
            }

            if (model.HasChanges)
            {
                model.SaveChanges();
            }

            
            if (pessoa != null)
            {
                if (marcar)
                {
                    PontuacaoUtils.Pontuar(pessoa, PontuacaoEnum.MarcarSolucaoComentario);
                }
                else
                {
                    PontuacaoUtils.Pontuar(pessoa, PontuacaoEnum.DesmarcarSolucaoComentario);
                }
            }

            return PartialView("_VerComentariosView", rec);
        }

        public PartialViewResult _IncluirReclamacao(string tipo)
        {
            Reclamacao rec = null;
            if (Session["rec"] != null)
            {
                rec = (Reclamacao) Session["rec"];
            }

            return PartialView(tipo == "m" ? "_IncluirReclamacaoMidia" : "_IncluirReclamacaoTexto", rec);
        }

        public ActionResult DesativarReclamacao(int Id)
        {
            var model = ConnectionDbClass.DataModel;

            var rec = model.Reclamacaos.FirstOrDefault(f => f.Id == Id);

            rec.IsAtivo = false;

            if (model.HasChanges)
            {
                model.SaveChanges();
            }

            var usuario = (Usuario)Session["Usuario"];

            return RedirectToAction("Perfil", "Usuario", usuario.Pessoa);
        }

        public ActionResult AcessarReclamacao(int Id)
        {
            var model = ConnectionDbClass.DataModel;

            var rec = model.Reclamacaos.FirstOrDefault(f => f.Id == Id);

            return View(rec);
        }

        public ActionResult AlterarReclamacao(int Id)
        {
            var model = ConnectionDbClass.DataModel;

            var rec = model.Reclamacaos.FirstOrDefault(f => f.Id == Id);

            Session["rec"] = rec;

            return View("IncluirReclamacao", rec); 
        }

        public ActionResult GravarReclamacao(Reclamacao reclamacao, HttpPostedFileBase file)
        {
            var usuario = (Usuario)Session["Usuario"];

            var model = ConnectionDbClass.DataModel;
            
            if (file != null) { 
                if (file.ContentType.Contains("image"))
                {
                    if (file.ContentLength > 2097152)
                    {
                        ViewBag.Erro = "O Arquivo de imagem ultrapassa o limite de 2Mb.";
                        return View("IncluirReclamacao");
                    }
                }
                else if (file.ContentType.Contains("video"))
                {
                    if (file.ContentLength > 26214400)
                    {
                        ViewBag.Erro = "O Arquivo anexo ultrapassa o limite de 25Mb.";
                        return View("IncluirReclamacao");
                    }
                }
                else
                {
                    ViewBag.Erro = "Somente é permitda a inclusão de fotos ou vídeos.";
                    return View("IncluirReclamacao");
                }

                if (file.ContentLength > 0)
                {
                    var fileName = "";
                    if (file.ContentType.Contains("image"))
                    {
                        if (string.IsNullOrEmpty(fileName))
                        {
                            fileName = "rec_" + usuario.Pessoa.Id + "_" + DateTime.Now.ToString("yyyyMd_hhmmss") + ".jpg";
                        }
                    }
                    else
                    {
                        string extensao = Path.GetExtension(file.FileName);

                        fileName = "rec_" + usuario.Pessoa.Id + "_" + DateTime.Now.ToString("yyyyMd_hhmmss") + extensao;
                    }

                    var path = Path.Combine(Server.MapPath("~/Images/Uploads/Queixa"), fileName );

                    reclamacao.Anexo = fileName;

                    file.SaveAs(path);

                    PontuacaoUtils.Pontuar(usuario.Pessoa, PontuacaoEnum.ReclamacaoEmMidia);
                }
            }

            if (string.IsNullOrEmpty(reclamacao.Descricao) || string.IsNullOrEmpty(reclamacao.Titulo))
            {

ouvidoria-social/Views/Usuario/AlterarPerfil.cshtml
@using System.Globalization
@using ouvidoria_social.Models.Adapter
@using Ouvidoria_Social_DataAccess
@model Ouvidoria_Social_DataAccess.Pessoa

@{
    ViewBag.Title = "AlterarPerfil";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var model = ConnectionDbClass.DataModel;

    var ufs = model.Ufs.ToList();
    ufs.Insert(0, new Uf()
    {
        Nome = "Estado",
        Uf1 = "-"
    });

    //var estados = new SelectList(ufs, "uf1", "Nome", Model.Cidade.Uf);

    //var cidades = model.Cidades.Where(w => w.Uf == Model.Cidade.Uf).ToList();

    //var city = new SelectList(cidades, "id", "Cidade1", Model.Cidade.Id);
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#Ufs").change(function () {
            listaCidade($(this).val());
        });
    });

    $("input").on("change", function() {
        this.setAttribute(
            "data-date",
            moment(this.value, "YYYY-MM-DD")
            .format(this.getAttribute("data-date-format"))
        )
    }).trigger("change");

    //chamada ajax para a Action ListaCidade
    //passando como parâmetro a Estado selecionado
    function listaCidade(uf) {

        var url = "@Url.Action("ListaCidade", "Autenticacao")" + "/?uf=" + uf;

            $.getJSON(url, listaCidadeCallBack);
        }
        //função que irá ser chamada quando terminar
        //a chamada ajax
        function listaCidadeCallBack(json) {
            $("#Id_cidade :gt(0)").remove();

            var cidade = "arroba Model.Cidade.Id";

            $(json).each(function () {
                if (cidade == this.Id) {

                    alert(cidade);
                    $("#Id_cidade").append("<option selected='selected' value='" + this.Id + "'>" + this.Cidade + "</option>");
                } else {
                    $("#Id_cidade").append("<option value='" + this.Id + "'>" + this.Cidade + "</option>");
                }
            });
        }
</script>

<div class="container">

    @Html.Partial("_HeaderPerfilView")
    <br />
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading text-center">
                    <h3 class="panel-title">Informaçoes Básicas - Alteração de Perfil</h3>
                </div>
                @using (Html.BeginForm("GravarPerfil", "Usuario", FormMethod.Post))
                {
                    <div class="panel-body">
                        @Html.LabelFor(l => l.Nome)<br/>
                        @Html.TextBoxFor(l => l.Nome, new Dictionary<string, object>() {{"autofocus", "autofocus"}, {"maxlenght", 100}, {"size", 90}, {"class", "form-control"}})<br/>

                        <!--
                        @Html.LabelFor(l => l.Apelido)<br/>
                        @Html.TextBoxFor(l => l.Apelido, new Dictionary<string, object>() {{"maxlenght", 100}, {"size", 90}, {"class", "form-control"}})<br/>
                        -->
                        
                        <!--
                        @Html.Label("Telefone (Fixo ou Celular)")<br/>
                        @Html.TextBoxFor(l => l.Telefone, new Dictionary<string, object>() {{"maxlenght", 11}, {"type", "tel"}, {"size", 20}, {"class", "form-control"}})<br/>
                        -->

                        @Html.Label("E-Mail")<br/>
                        @Html.TextBoxFor(l => l.Email, new Dictionary<string, object>() {{"maxlenght", 100}, {"type", "email"}, {"size", 90}, {"class", "form-control"}})<br/>

                        <!--
                        @Html.Label("Estado")

                        @Html.Label("Cidade")<br/>
                        -->

                        @Html.Label("Descrição")<br/>
                        @Html.TextAreaFor(l => l.Descricao, new Dictionary<string, object>() {{"maxlenght", 500}, {"size", 80}, {"class", "form-control"}})<br/>

                        @Html.HiddenFor(l => l.Id)
                    </div>
                    <div class="panel-footer text-center">
                        <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-floppy-disk"></i> Gravar</button>
                        <a class="btn btn-primary" href="@Url.Action("Perfil", "Usuario", new {Id = Model.Id})"><i class="glyphicon glyphicon glyphicon-ban-circle"></i> Cancelar</a>
                    </div>
                }
            </div>
        </div>
        <div class="col-md-6">
            @Html.Partial("_AlterarUsuarioView", new UsuarioAdapter());
        </div>
    </div>
</div>

ouvidoria-social/Views/Usuario/_NotificacoesPerfilView.cshtml
@using ouvidoria_social.Models.Adapter
@using Ouvidoria_Social_DataAccess
@model List<Ouvidoria_Social_DataAccess.Log_participapao>

@{
    Usuario user = null;
    if (Session["Usuario"] != null)
    {
        user = (Usuario)Session["Usuario"];
    }
}

<div class="row">
    <div class="col-md-12 text-right">
        <a class="label label-primary" href="@Url.Action("MarcarNotificacoesLidas", "Home", new {idPessoa = user.Id_pessoa})"><i class="glyphicon glyphicon-check"></i> Marcar como Lidas</a>
    </div>
</div>
<hr/>

@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div class='row'>
                <div class='col-md-3'>
                    @if (!string.IsNullOrEmpty(item.Pessoa.Avatar))
                    {
                        var urlPessoa = Url.Content("~/Images/Uploads/Avatar/" + item.Pessoa.Avatar);

                        <a href='@Url.Action("Perfil", "Usuario", new {Id = item.Id_pessoa})'>
                            <img class='img-circle' src='@urlPessoa' width='32' height='32'> 
                            @item.Pessoa.Nome
                        </a>
                    }
                    else
                    {
                        var sobrenome = "";
                        var nomes = item.Pessoa.Nome.Trim().Split(' ');
                        if (nomes.Count() >= 2)
                        {
                            sobrenome = nomes[nomes.Count() - 1].ToUpper().Substring(0, 1);
                        }

                        <a class="btn btn-primary btn-sm" style="border-radius: 100px" href='@Url.Action("Perfil", "Usuario", new {Id = item.Id_pessoa})'>
                            @(item.Pessoa.Nome.ToUpper().Substring(0, 1) + sobrenome)
                        </a>
                        <a href='@Url.Action("Perfil", "Usuario", new {Id = item.Id_pessoa})'>
                            @item.Pessoa.Nome
                        </a> 
                    }

                </div>
                <div class='col-md-9'>
                    @{
                        var str = "";

                        var nome = item.Pessoa.Nome;
                        if (nome.Length > 5)
                        {
                            nome = nome.Substring(0, 5) + "...";
                        }

                        var icon = "";

                        if (item.Tipo.Contains("Descur"))
                        {
                            icon = "<i class='glyphicon glyphicon-thumbs-down'></i> ";
                        }
                        else if (item.Tipo.Contains("Curt"))
                        {
                            icon = "<i class='glyphicon glyphicon-thumbs-up'></i> ";
                        }
                        else if (item.Tipo.ToLower().Contains("soluc"))
                        {
                            icon = "<i class='glyphicon glyphicon-check'></i> ";
                        }
                        else if (item.Tipo.Contains("Acess"))
                        {
                            icon = "<i class='glyphicon glyphicon-share-alt'></i> ";
                        }
                        else if (item.Tipo.Contains("Coment"))
                        {
                            icon = "<i class='glyphicon glyphicon-comment'></i> ";
                        }

                        if ((item.Tipo == "Descurtiu") || (item.Tipo == "Acessou") || (item.Tipo == "Curtiu") || (item.Tipo == "Solucionou"))
                        {
                            str = icon +
                                  "<a href='" + Url.Action("Perfil", "Usuario", new { Id = item.Pessoa.Id }) + "'>" + nome + "</a> " + item.Tipo +
                                  " a " +
                                  "<a href='" + Url.Action("AcessarReclamacao", "Ouvidoria", new { Id = item.Reclamacao.Id }) + "'>Reclamação</a>";
                        }
                        else
                        {
                            str = icon +
                                  "<a href='" + Url.Action("Perfil", "Usuario", new { Id = item.Pessoa.Id }) + "'>" + nome + "</a> " + item.Tipo +
                                  " na " +
                                  "<a href='" + Url.Action("AcessarReclamacao", "Ouvidoria", new { Id = item.Reclamacao.Id }) + "'>Reclamação</a>";
                        }
                    }

                    @Html.Raw(str);
                </div>
            </div>
        </div>
    </div>
}

ouvidoria-social/Views/Usuario/_ReclamacaoInstituicaoView.cshtml
@using Ouvidoria_Social_DataAccess
@model List<Ouvidoria_Social_DataAccess.Reclamacao>

@{
    var isThisUser = (bool)ViewData["isThisUser"];
    var reclamacoes = Model.Where(w => w.IsAtivo == true).OrderByDescending(o => o.DataHora).Take(10);
}

<div class="col-md-9">
    <div class="table-responsive">
        <div class="panel panel-primary">
            <div class="panel-heading text-center">
                <h3 class="panel-title"><i class="glyphicon glyphicon-comment"></i>Reclamações sobre a Instituição</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Título</th>
                            <th>Departamento</th>
                            <th class="text-right">Comentários</th>
                            <th>Usuario</th>
                            <th style="text-align: center;">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var rec in reclamacoes)
                        {
                            var iSolucionado = rec.Comentarios.Any(a => a.IsSolucao == true);

                            <tr>
                                <td class="text-center">
                                    @if (isThisUser)
                                    {
                                        if (!iSolucionado)
                                        {
                                            <a href="@Url.Action("DesativarReclamacao", "Ouvidoria", new {Id = rec.Id})">
                                                <i class="glyphicon glyphicon-remove"></i>
                                            </a>
                                        }
                                    }
                                </td>
                                <td class="text-center">
                                    @if (isThisUser)
                                    {
                                        if (!iSolucionado)
                                        {
                                            <a href="@Url.Action("AlterarReclamacao", "Ouvidoria", new {Id = rec.Id})">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                            </a>
                                        }
                                    }
                                </td>
                                <td>
                                    <a href="@Url.Action("AcessarReclamacao", "Ouvidoria", new {Id = rec.Id})">
                                        @rec.Titulo
                                    </a>
                                </td>
                                <td>
                                    @rec.Departamento
                                </td>
                                <td class="text-right">
                                    @rec.Comentarios.Count()
                                </td>
                                <td>
                                    @if (rec.Instituicao != null)
                                    {
                                        @Html.ActionLink(rec.Pessoa.Nome, "Perfil", new { Id = rec.Id_pessoa })
                                    }
                                </td>
                                <td style="text-align: center;">
                                    @if (iSolucionado)
                                    {
                                        <i class="glyphicon glyphicon-ok-sign text-center"></i>
                                    }
                                    else
                                    {
                                        <i class="glyphicon glyphicon-remove-sign text-center"></i>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot class="text-left">
                        <tr>
                            <td colspan="3"><strong>Total de Registros: @reclamacoes.Count()</strong></td>
                            <td colspan="4">
                                <strong>
                                    Legenda: <i class="glyphicon glyphicon-ok-sign text-center"></i> Solucionado
                                    <i class="glyphicon glyphicon-remove-sign text-center"></i> Não Solucionado
                                </strong>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="panel-footer text-right">
                <div class="row">
                    <div class="col-md-8 text-left vertical-align">
                        <small><strong>Serão exibidos apenas os 10 primeiros resultados.</strong></small>
                    </div>
                    <div class="col-md-4 text-right">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>